on:
  workflow_call:
    inputs:
      formula:
        required: true
        type: string
    outputs:
      tag-array:
        value: ${{ jobs.bottle.outputs.tag-array }}

jobs:
  bottle:
    runs-on: ubuntu-latest
    outputs:
      tag-array: ${{ steps.bottle-and-tag.outputs.tag-array }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: Homebrew/actions/setup-homebrew@master

      - uses: actions/download-artifact@v3
        with:
          name: formula-bottles

      - uses: fregante/setup-git-user@v2

      - uses: dcarbone/install-jq-action@v1.0.1

      - uses: charitybell/set-git-url-action@main
        with:
          token: ${{ github.token }}

      - name: bottle and tag
        id: bottle-and-tag
        run: |
          brew update
          declare -A tag_array
          for formula in $(echo '${{ inputs.formula }}' | jq -rc .[]); do
            FORMULA_NAME="$(basename $formula .rb)"
            FORMULA_TAP=$(echo ${{ github.repository }} | cut -d / -f 1)/$(echo ${{ github.repository }} | cut -d / -f 2 | cut -d - -f 2)/$FORMULA_NAME
            FORMULA_VERSION=$(jq -cr .['"'$FORMULA_TAP'"'].formula.pkg_version ${FORMULA_NAME}-*.bottle.json | head -n 1)
            TAG_MESSAGE="${FORMULA_NAME}-${FORMULA_VERSION}"

            brew bottle --merge --write \
              --root-url ${{ github.server_url }}/${{ github.repository }}/releases/download/$FORMULA_NAME/$FORMULA_VERSION \
              ${FORMULA_NAME}-*.bottle.*json

            git tag -a "$TAG_MESSAGE" -m "$TAG_MESSAGE"
            tag_array["$formula"]="$TAG_MESSAGE"
          done
          git -c push.default=current push --tags
          git -c push.default=current push

          output_json=$(comma=''; echo -n '{' ; for key in "${!tag_array[@]}"; do echo -n $comma '"'"$key"'"':'"'"${tag_array[$key]}"'"'; comma=","; done; echo -n "}")
          echo "tag-array=$output_json" >> $GITHUB_OUTPUT
