name: build and release

on: [pull_request]

jobs:  
  prepare:
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: Formula/*.rb
          json: true
          
      - name: print changed files
        id: print-changes
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}
          echo ${{ fromJSON(steps.changed-files.outputs.all_changed_files) }}
  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        formula: ${{ fromJSON(needs.prepare.outputs.changed_files) }}
    steps:
      - name: build bottle
        run: |
          brew install --build-bottle ${{ matrix.formula }}
