name: build and release

on: [pull_request]

jobs:  
  prepare:
    outputs:
      matrix: ${{ steps.set-output-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: Formula/*.rb
          json: true
          
      - name: set output matrix
        id: set-output-matrix
        run: |
          #echo 'matrix={\"formula\": ${{ steps.changed-files.outputs.all_changed_files }} }' >> $GITHUB_OUTPUT
          echo "matrix={\"formula\": [\"Formula/stash.rb\"]}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: build bottle
        run: |
          #brew install --build-bottle ${{ matrix.formula }}
          echo '${{ needs.prepare.outputs.matrix }}'
