name: audit pr

on: [pull_request]

jobs:  
  prepare:
    outputs:
      matrix: ${{ steps.set-output-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: Formula/*.rb
          json: true
          
      - name: set output matrix
        id: set-output-matrix
        run: |
          echo "matrix={\"formula\": ${{ steps.changed-files.outputs.all_changed_files }} }" >> $GITHUB_OUTPUT
  audit:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: audit bottle (${{ matrix.formula }})
        run: |
          brew audit --online ${{ matrix.formula }}
