name: build and release

on: [pull_request]

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
	  with:
		fetch-depth: 2

	- name: Set up Homebrew
      id: set-up-homebrew
	  uses: Homebrew/actions/setup-homebrew@master

	- name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: Formula/*.rb
        json: true

	- name: Run step if any of the listed files above change
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo {{ steps.changed-files.outputs.all_changed_files }}
