name: test-bot

on: [pull_request]

jobs:
  test-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: Homebrew/actions/setup-homebrew@master

      - run: brew test-bot && ls || ls
