on:
  workflow_dispatch:
    inputs:
      formula:
        required: true
        description: Name of formula to build, without "<user>/<repo>/" prefix
        type: string
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ vars.RUNNERS }}'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

  call:
    needs: [prepare]
    strategy:
      matrix:
        os: ${{ fromJSON(vars.RUNNERS) }}
    uses: ./.github/workflows/build.yml
    with:
      formula: ${{ github.event.inputs.formula }}
      os: ${{ matrix.os }}

  check:
    needs: [call]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: formula-bottles
      - run: |
          ls
          cat ${{github.event.inputs.formula }}.txt
          [ "${{ github.event.inputs.formula }}" == "$(cat ${{github.event.inputs.formula }}.txt)" ]
