on:
  workflow-call:
    inputs:
      formula:
        required: true
        description: Name of formula to build, without "<user>/<repo>/" prefix
        type: string
      os:
        required: true
        type: choice
        description: What operating system to build on
        options: ${{ fromJSON(vars.RUNNERS) }}
      config-path:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build.yml
        with:
          formula: ${{ github.event.inputs.formula }}
          os: ${{ github.event.inputs.os }}
      - uses: actions/download-artifact@v3
        with:
          name: formula-bottles
      - run: |
          ls
          cat ${{github.event.inputs.formula }}.txt
          [ "${{ github.event.inputs.formula }}" == "$(cat ${{github.event.inputs.formula }}.txt)" ]
